pre_packaging

diff --git a/packages/sentimentr-service-broker/pre_packaging b/packages/sentimentr-service-broker/pre_packaging
--- a/packages/sentimentr-service-broker/pre_packaging
+++ b/packages/sentimentr-service-broker/pre_packaging
@@ -4,13 +4,35 @@ set -e -x
 JAVA_VERSION=jdk1.8.0_45
 JAVA_TARBALL=jdk-8u45-linux-x64.gz
 
-mkdir -p /tmp/java
-tar zxf java/${JAVA_TARBALL} -C /tmp/java
-export JAVA_HOME=/tmp/java/${JAVA_VERSION}
+# Make sure we can see uname
+export PATH=$PATH:/bin:/usr/bin
+
+###############
+if [ `uname` = "Linux" ]; then
+  mkdir -p /tmp/java
+  tar zxf java/${JAVA_TARBALL} -C /tmp/java
+  export JAVA_HOME=/tmp/java/${JAVA_VERSION}
+  export PATH=$JAVA_HOME/bin:$PATH
+else
+  if [ ! -d $JAVA_HOME ]; then
+    echo "JAVA_HOME properly set is required for non Linux/Darwin builds."
+    exit 1
+  fi
+fi
+
+###############
+
+
 
 cd ${BUILD_DIR}/sentimentr-service-broker
-curl -v http://www.google.de
 
 ./gradlew assemble
 
 cp -a build/libs/sentimentr-service-broker.war ${BUILD_DIR}/sentimentr-service-broker.jar
+
+#clean build data
+./gradlew clean
+
+rm -rf tmp/java
+
+#${BUILD_DIR}/login/.clean-cf-release-build
diff --git a/packages/sentimentr/pre_packaging b/packages/sentimentr/pre_packaging
--- a/packages/sentimentr/pre_packaging
+++ b/packages/sentimentr/pre_packaging
@@ -6,16 +6,38 @@ MAVEN_TARBALL=${MAVEN_VERSION}-bin.tar.gz
 JAVA_VERSION=jdk1.8.0_45
 JAVA_TARBALL=jdk-8u45-linux-x64.gz
 
-mkdir -p /tmp/java
-tar zxf java/${JAVA_TARBALL} -C /tmp/java
-export JAVA_HOME=/tmp/java/${JAVA_VERSION}
+# Make sure we can see uname
+export PATH=$PATH:/bin:/usr/bin
 
-mkdir -p /tmp/mvn
-tar zxf mvn/${MAVEN_TARBALL} -C /tmp/mvn
-export MAVEN_HOME=${BOSH_COMPILE_TARGET}/${MAVEN_VERSION}
-export PATH=/tmp/mvn/bin:$PATH
+###############
+if [ `uname` = "Linux" ]; then
+  mkdir -p /tmp/java
+  tar zxf java/${JAVA_TARBALL} -C /tmp/java
+  export JAVA_HOME=/tmp/java/${JAVA_VERSION}
+  export PATH=$JAVA_HOME/bin:$PATH
+
+  mkdir -p /tmp/mvn
+  tar zxf mvn/${MAVEN_TARBALL} -C /tmp/mvn
+  export MAVEN_HOME=/tmp/mvn/${MAVEN_VERSION}
+  export PATH=$MAVEN_HOME/bin:$PATH
+else
+  if [ ! -d $JAVA_HOME ]; then
+    echo "JAVA_HOME properly set is required for non Linux builds."
+    exit 1
+  fi
+fi
+
+###############
 
 cd ${BUILD_DIR}/sentimentr-service
 mvn -B -e clean install -DskipTests=true
 
 cp -a target/sentiment-0.0.1-SNAPSHOT.jar ${BUILD_DIR}/sentimentr.jar
+
+#clean build data
+mvn clean
+
+rm -rf tmp/java
+rm -rf tmp/mvn
+
+#${BUILD_DIR}/login/.clean-cf-release-build
